### ISSUE TITLE
On the issue of features_arr_concat

### ISSUE THREAD

**Issue by GoodMorningAndGoodEvening** [dipika-singhania/ICC-Semi-Supervised-TAS#7]
Hi dipika,
First of all, thank you very much for your excellent work!
When I experimented with the GTEA dataset, it generated the following error:

Traceback (most recent call last):
  File "E:\pycharm2021.3\pythonProject\Semi-supervised\ICC-Semi-Supervised-TAS-main\runcodes\unsupervised_traineval.py", line 600, in <module>
    model = model_pipeline(args)
  File "E:\pycharm2021.3\pythonProject\Semi-supervised\ICC-Semi-Supervised-TAS-main\runcodes\unsupervised_traineval.py", line 251, in model_pipeline
    train(model, train_loader, criterion, optimizer, args, test_loader, postprocessor)
  File "E:\pycharm2021.3\pythonProject\Semi-supervised\ICC-Semi-Supervised-TAS-main\runcodes\unsupervised_traineval.py", line 571, in train
    acc, all_result = get_linear_acc(args.label_id_csv, dump_dir, args.ground_truth_files_dir, args.perdata,
  File "E:\pycharm2021.3\pythonProject\Semi-supervised\ICC-Semi-Supervised-TAS-main\utility\perform_linear.py", line 263, in get_linear_acc
    feat_labels_videoids_dict = get_gathered_features_labels_videoids(ground_truth_dir, feature_dump_dir, 
  File "E:\pycharm2021.3\pythonProject\Semi-supervised\ICC-Semi-Supervised-TAS-main\utility\perform_linear.py", line 43, in get_gathered_features_labels_videoids
    features_arr_concat = np.concatenate(features_arr_concat, axis=0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 943 and the array at index 1 has size 1178

I printed out the features_arr_concat and found that they are matrices of different sizes, so they cannot be connected. How can I solve this problem?
Best wishes
Thanks.

**Comment by ee2110** [comment]
Hi @GoodMorningAndGoodEvening , I was wondering if you have found any solution or workaround for the issue? It would be really helpful to know how you approached it, thank you!
